# Generated by Django 3.1.7 on 2021-03-15 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_file', models.FileField(upload_to='song_files/')),
            ],
        ),
        migrations.CreateModel(
            name='Songs_Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=80)),
                ('album_img', models.ImageField(upload_to='album_images/')),
                ('artist_name', models.CharField(max_length=50)),
                ('genre_name', models.CharField(default='miscellaneous', max_length=50)),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.songs', unique=True)),
            ],
        ),
    ]
