# Generated by Django 3.1.7 on 2021-03-16 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs_metadata',
            name='song_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.songs'),
        ),
    ]
