# Generated by Django 3.1.7 on 2021-03-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210316_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='song_file',
            field=models.FileField(unique=True, upload_to='song_files/'),
        ),
    ]
